- assignment-v2/test-case-0.json
- assignment-v2/test-case-1.json
- assignment-v2/test-case-2.json
- assignment-v2/test-case-3.json
- rac-experiments-v3.json
To support consistency between the RAC API and the test files:
* return stringified json in the `value` field of the variation
* continue returning json in the `typedValue` field of the variation
**Fixups**
* added `valueType` field to all test cases to avoid test code needing to support default value - we control these files and its ok to go back and add this
* added `overrides` and `typedOverrides` fields where they are missing since that meets the RAC API spec
> json variation values are string encoded

- rac-experiments-v3-obfuscated.json
Generated by this script: https://github.com/Eppo-exp/js-client-sdk-common/pull/24/files#diff-b77e6b71bcefeeaea5d0e6da2216201d4cd513f0da4132421f03084ee3a22b82
I think it's helpful to have a script somewhere to generate this programmatically, although I don't know if leaving it in the common sdk code makes the most sense.
Hashes the flag keys
And also obfuscates the `value`, `operator`, and `attribute` in each of the conditions in the rules, e.g.
```
"rules": [
{
"allocationKey": "allocation-experiment-4",
"conditions": [
{
"value": [
"9e304d4e8df1b74cfa009913198428ab",
"c31b32364ce19ca8fcd150a417ecce58"
],
"operator": "27457ce369f2a74203396a35ef537c0b",
"attribute": "913f9c49dcb544e2087cee284f4a00b7"
},
{
"value": "MQ==",
"operator": "cd6a9bd2a175104eed40f0d33a8b4020",
"attribute": …
```
> Add obfuscated rac file

- rac-experiments-v3.json
This change adds the `algorithmType` field to our test RAC in two places:
1. An existing allocation, where its value is always `CONSTANT`
2. A new flag and allocation with a `CONTEXTUAL_BANDIT`
The reason to do this is to make sure the presence (or later, lack of presence) of these fields doesn't break existing SDKs.
This will be made easier by the tests automatically running on push to main once pull request #3 is merged.
> Add algorithmType to test RAC

- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
- ufc/tests/test-case-comparator-operator-flag.json
- ufc/tests/test-case-invalid-value-flag.json
- ufc/tests/test-case-null-operator-flag.json
- ufc/tests/test-case-semver-flag.json
- ufc/tests/test-case-start-and-end-date-flag.json
Adding extra tests to the test suite to make sure all SDKs handle these correctly:
- An invalid type: added an integer flag with a non-integer variation. This should return the default value (based on discussion with Aaron)
- A semver test: making sure semantic versions are handled correctly
- A comparator test: making sure numerical comparisons are handled correctly
- Start and end date test: making sure all SKDs adhere to start and end dates on allocations (this test will break in 2052)
- Null operator test: making sure we handle null and non-null conditions correctly
> Add additional tests for the UFC

- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
Removing optional fields from some additional flags for better test coverage. Currently these fields are only missing for the start-end date test and hence when that one fails it is not obvious that the problem isn't with start and end dates.
> [UFC] Remove some optional fields

- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
- ufc/tests/test-case-boolean-one-of-matches.json
Adds a test case for when subject attribute value is null. In that case, no allocation should match.
> [ufc] add null attribute test

- ufc/tests/test-case-boolean-one-of-matches.json
- ufc/tests/test-case-comparator-operator-flag.json
- ufc/tests/test-case-disabled-flag.json
- ufc/tests/test-case-empty-flag.json
- ufc/tests/test-case-integer-flag.json
- ufc/tests/test-case-invalid-value-flag.json
- ufc/tests/test-case-kill-switch-flag.json
- ufc/tests/test-case-new-user-onboarding-flag.json
- ufc/tests/test-case-no-allocations-flag.json
- ufc/tests/test-case-null-operator-flag.json
- ufc/tests/test-case-numeric-flag.json
- ufc/tests/test-case-numeric-one-of.json
- ufc/tests/test-case-regex-flag.json
- ufc/tests/test-case-semver-flag.json
- ufc/tests/test-case-start-and-end-date-flag.json
- ufc/tests/test-flag-that-does-not-exist.json
- ufc/tests/test-json-config-flag.json
- ufc/tests/test-no-allocations-flag.json
updates existing test data to support new "assignment details" which provide end-users information on how an assignment happened
- first commit is just formatting changes
- second commit adds new "assignmentDetails" object
> FF-2498 Assignment Details test data

- ufc/bandit-flags-v1.json
- ufc/bandit-models-v1.json
- ufc/bandit-tests/test-case-bandit-does-not-exist.json
- ufc/bandit-tests/test-case-bandit-no-actions.json
- ufc/bandit-tests/test-case-banner-bandit-uk-only.json
- ufc/bandit-tests/test-case-banner-bandit.json
- ufc/bandit-tests/test-case-non-bandit-flag.json
- ufc/bandit-tests/test-case-non-bandit-integer-flag.json
Adds test cases that cover:
* Number passed as a subject categorical attribute
* Non-number passed as a subject numeric attribute
* Number passed as an action categorical attribute
* Non-number passed as an action numeric attribute
The tests are designed with assignments close to the boundary of the action weights so that if the numbers are not treated as categorical attributes and weighted appropriately, the tests will fail.
> Add test cases for numbers passed as categorical attributes

- ufc/bandit-flags-v1.json
- ufc/bandit-models-v1.json
- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
- ufc/tests/test-case-boolean-one-of-matches.json
- ufc/tests/test-case-comparator-operator-flag.json
- ufc/tests/test-case-disabled-flag.json
- ufc/tests/test-case-empty-flag.json
- ufc/tests/test-case-integer-flag.json
- ufc/tests/test-case-invalid-value-flag.json
- ufc/tests/test-case-kill-switch-flag.json
- ufc/tests/test-case-new-user-onboarding-flag.json
- ufc/tests/test-case-null-operator-flag.json
- ufc/tests/test-case-numeric-flag.json
- ufc/tests/test-case-numeric-one-of.json
- ufc/tests/test-case-regex-flag.json
- ufc/tests/test-case-semver-flag.json
- ufc/tests/test-case-start-and-end-date-flag.json
- ufc/tests/test-flag-that-does-not-exist.json
- ufc/tests/test-json-config-flag.json
Includes `environment` and `allocation.name` in UFC test data
> FF-2526 include environment and allocation.name in UFC response

- ufc/bandit-tests/test-case-banner-bandit-uk-only.dynamic-typing.json
- ufc/bandit-tests/test-case-banner-bandit-uk-only.json
- ufc/bandit-tests/test-case-banner-bandit.dynamic-typing.json
- ufc/bandit-tests/test-case-banner-bandit.json
PR #36 added a couple of test cases for handling incorrectly-typed attributes. While these tests are important for dynamically-typed languages, they should be skipped in statically-typed languages because a type system ensures this input is impossible.
Having these test cases in the same file is problematic as it fails test file parsing and requires a lot of special handling just to skip offending test cases.
This commit copies such test cases into ".dynamic-typing.json" files (so they are easy to ignore) and removes/fixes offending data in original files (so statically-typed languages see same test cases).
> Split test cases for dynamically-typed languages

- ufc/tests/test-case-boolean-one-of-matches.json
- ufc/tests/test-case-comparator-operator-flag.json
- ufc/tests/test-case-disabled-flag.json
- ufc/tests/test-case-empty-flag.json
- ufc/tests/test-case-integer-flag.json
- ufc/tests/test-case-invalid-value-flag.json
- ufc/tests/test-case-kill-switch-flag.json
- ufc/tests/test-case-new-user-onboarding-flag.json
- ufc/tests/test-case-null-operator-flag.json
- ufc/tests/test-case-numeric-flag.json
- ufc/tests/test-case-numeric-one-of.json
- ufc/tests/test-case-regex-flag.json
- ufc/tests/test-case-semver-flag.json
- ufc/tests/test-case-start-and-end-date-flag.json
- ufc/tests/test-flag-that-does-not-exist.json
Fixes a mistake in the structure of the assignmentDetails object. See original PR: https://github.com/Eppo-exp/sdk-test-data/pull/38
> FF-2526 fix tests for assignmentDetails object

- ufc/bandit-flags-v1.json
- ufc/bandit-models-v1.json
- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
- ufc/tests/test-case-boolean-one-of-matches.json
- ufc/tests/test-case-comparator-operator-flag.json
- ufc/tests/test-case-disabled-flag.json
- ufc/tests/test-case-empty-flag.json
- ufc/tests/test-case-integer-flag.json
- ufc/tests/test-case-invalid-value-flag.json
- ufc/tests/test-case-kill-switch-flag.json
- ufc/tests/test-case-new-user-onboarding-flag.json
- ufc/tests/test-case-null-operator-flag.json
- ufc/tests/test-case-numeric-flag.json
- ufc/tests/test-case-numeric-one-of.json
- ufc/tests/test-case-regex-flag.json
- ufc/tests/test-case-semver-flag.json
- ufc/tests/test-case-start-and-end-date-flag.json
- ufc/tests/test-flag-that-does-not-exist.json
- ufc/tests/test-json-config-flag.json
Reverts allocation.name (see thread https://eppo-group.slack.com/archives/C06N7AA6M5F/p1719864923087059?thread_ts=1719438261.986839&cid=C06N7AA6M5F)
This reverts commit e169514d1c6e91bec6cd89fa956d18846573fcd3.
> Revert "FF-2526 fix tests for assignmentDetails object (#40)"

- ufc/bandit-tests/test-case-banner-bandit.dynamic-typing.json
- ufc/bandit-tests/test-case-banner-bandit.json
Use values such that a different action will be selected if zip code is treated as numeric instead of categorical.
This was proved out for a JavaScript-client-specific test in [this PR](https://github.com/Eppo-exp/js-client-sdk-common/pull/108/files#diff-c3451b91ff71fe92808fe19fd6c58fe9dece0f29837d534e1ca186516153226fR302).
> Fix up the zip code as a categorical attribute test

- ufc/bandit-flags-v1.json
- ufc/bandit-models-v1.json
- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
- ufc/tests/test-case-boolean-one-of-matches.json
- ufc/tests/test-case-comparator-operator-flag.json
- ufc/tests/test-case-disabled-flag.json
- ufc/tests/test-case-empty-flag.json
- ufc/tests/test-case-integer-flag.json
- ufc/tests/test-case-invalid-value-flag.json
- ufc/tests/test-case-kill-switch-flag.json
- ufc/tests/test-case-new-user-onboarding-flag.json
- ufc/tests/test-case-null-operator-flag.json
- ufc/tests/test-case-numeric-flag.json
- ufc/tests/test-case-numeric-one-of.json
- ufc/tests/test-case-regex-flag.json
- ufc/tests/test-case-semver-flag.json
- ufc/tests/test-case-start-and-end-date-flag.json
- ufc/tests/test-flag-that-does-not-exist.json
Re-applies `environmentName` (without `allocation.name`) after reverting both `environmentName + allocation.name` in https://github.com/Eppo-exp/sdk-test-data/pull/41
> FF-2526 Test data for environment as part of UFC response

- ufc/bandit-flags-v1.json
`totalShards` is a required field.
> fix: add missing totalShards

- ufc/bandit-tests/test-case-bandit-no-actions.json
🎟️ **Ticket:** [FF-2813 - Update shared test data for no actions scenario](https://linear.app/eppo/issue/FF-2813/update-shared-test-data-for-no-actions-scenario)
🗨️ **Slack:** ["...I think there's a problem in our JS common SDK with how we handle invoking `getBanditAction()` with an empty action set...."](https://eppo-group.slack.com/archives/C05R6BK5BB9/p1721149341928549)
There may be scenarios where an empty set of actions is passed to the bandit. Before, we decided to return the default variation without logging anything if the flag had a bandit. However, this is not desirable as some users may never see the bandit due to targeting rules.
We've decided to change the behavior, and if a variation is assigned, log and return it. If the assigned variation is a bandit, and …
> Adjust and expand the no actions scenario tests

- ufc/bandit-flags-v1.json
Related [Backend PR](https://github.com/Eppo-exp/eppo/pull/9972)
the `bandits` field of the `UFCResponse` is limited in the amount of information it can convey due to its structure and inability to change it without breaking all of the SDKs. So, a new field, `banditReferences` was introduced to satisfy the need to package a model version for any bandit referenced by a flag in the UFC. This allows for optimized loading of bandit models where the network fetch can be skipped if the SDK already has the required models.
Add section to test response file. SDKs will need modification to migrate to the new field
> Add `BanditReferences` to test data UFC response

- test-validation/validate-tests.spec.ts
- ufc/tests/test-case-invalid-value-flag.json
ASSIGNMENT_ERROR later in the evaluation process should not revert the previously-done evaluation and definitely should not list unmatched/matched allocations as "unevaluated."
> fix: preserve allocation evaluation details when ASSIGNMENT_ERROR

- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
- ufc/tests/test-json-array-config-flag.json
Broken behavior was observed in some SDKs when users create a json variation with top-level arrays.
* Adds a discrete test for this behavior to surface all broken SDKs and prevent regressions.
* Modeled on the existing JSON test but with array values instead of object.
> add test case for json array variation values (FF-2903)

- ufc/bandit-flags-v1.json
- ufc/bandit-models-v1.json
- ufc/bandit-tests/test-case-car-bandit.json
🎟️ **Ticket:** [FF-2996 - Update shared bandit tests to handle more edge cases](https://linear.app/eppo/issue/FF-2996/update-shared-bandit-tests-to-handle-more-edge-cases)
This PR adds a new bandit that powers a new test file with two test cases that check three edge cases:
- Default score is correctly applied
- Probability floor is correctly applied
- Top-scoring actions are tie-broken by name for weighting
> Tests for default score, probability floor, and top score tie-breaking

- .github/workflows/test-sdks.yml
[package requirement](https://github.com/Eppo-exp/node-server-sdk/blob/452239cc15280a43a40f58d8eee5d9da1ce00ba7/package.json#L59)
Previous test-run failure due to node version
Current test run (where failure is due to downstream tests actually failing at HEAD)
> fix: Bump node version in sdk-test workflow to 18.x as required by the package.

- .github/workflows/test-sdks-remote.yml
- .github/workflows/test-sdks.yml
No need to run the SDK unit tests when other parts of the repo change.
> Only run universal unit tests when the test data changes

- ufc/bandit-flags-v1.json
- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
🎟️ [FF-3337 - Indicate in UFC the format (e.g., obfuscated or not)](https://linear.app/eppo/issue/FF-3337/indicate-in-ufc-the-format-eg-obfuscated-or-not)
👯‍♀️ Related PR: [`eppo #10896 `](https://github.com/Eppo-exp/eppo/pull/10896)
🧪 Example Use In SDK: [`sdk-common-jdk #45`](https://github.com/Eppo-exp/sdk-common-jdk/pull/45/files#diff-94d43dd76278a8107f921a3ad51611ff78dc348d16fea70231526f6b2e96f0e3R83)
To explicitly indicate if a UFC file is obfuscated or not, we're adding a `format` field. Currently, it can be `server` (unobfuscated) or `client` (obfuscated).
> Include format field in UFC files to indicate if obfuscated or not

- ufc/bandit-flags-v1.json
- ufc/bandit-models-v1.json
- ufc/bandit-tests/test-case-bandit-cold-start.json
We want to test when a bandit has cold-started, e.g., no model parameters have been generated yet.
Note that the UFC is currently inconsistent with the name of the version of a cold-started bandit, with "`cold start`" used in the model parameters and `null` used in the UFC. We need to align on one to avoid errors.
The plan is to align on committing the `v` prefix and using the `"cold start"` placeholder as this is more SDK friendly.
See all passing with `cold start` as the model version: https://github.com/Eppo-exp/sdk-test-data/actions/runs/11715905905/job/32633092353?pr=71
Mixed Results when `null` is the model version: https://github.com/Eppo-exp/sdk-test-data/actions/runs/11715993935/job/32633330226?pr=71
This PR updates the test data to match that plan.
> Include a cold start bandit test case

- package-testing/sdk-test-runner/Dockerfile
- package-testing/sdk-test-runner/README.md
- package-testing/sdk-test-runner/src/app.ts
- package-testing/sdk-test-runner/test-sdk.sh
Each SDK relay requires a build process to be executed in an environment configured to do so.
- Specify a platform-specific build-and-run script
- use `docker-run.sh` if available
- properly exit runner script with code
> feat: SDK relay launch script options

- package-testing/php-sdk-relay/.env.EXAMPLE
- package-testing/php-sdk-relay/Dockerfile
- package-testing/php-sdk-relay/docker-run.sh
- package-testing/php-sdk-relay/src/Config.php
- package-testing/sdk-test-runner/README.md
- package-testing/sdk-test-runner/test-sdk.sh
The `EPPO_BASE_URL` environment variable is a handy combination of `EPPO_API_HOST` and `EPPO_API_PORT. It's better to use this variable in the SDK relay nodes instead of checking for the presence of a port and appending it to the host in each node. (Here, and "SDK Node" refers to an SDK relay server or client, like the [php-relay](https://github.com/Eppo-exp/sdk-test-data/tree/main/package-testing/php-sdk-relay))
Also, quick fix to the PHP docker run to remove the container after running. Makes local runs much easier.
> feat: Testing cluster: `EPPO_BASE_URL` environment variable

- .github/workflows/build-and-push.yml
- .github/workflows/release-sdk-test-runner.yml
- .github/workflows/release-sdk-testing-api.yml
- .github/workflows/validate-test-data.yml
towards FF-3104
We want to use prebuilt docker images to make rolling out a test cluster faster
- Secrets and Variables are set on this repository (via admin UI)
- common workflow to build and push an image to the GAR
- workflows for each of the images we want to build.
> feat: github workflows to build and push (to GCP Artifact Reg) images

- .github/workflows/test-sdks-remote.yml
- .github/workflows/test-sdks.yml
- ufc/tests/test-case-integer-flag.json
🎟️ towards FF-3085
👯‍♂️ **Related PRs**
- [eppo-multiplatform](https://github.com/Eppo-exp/eppo-multiplatform/pull/73)
- #57
- #58
- #59
Changes are often made to the [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data) repository to capture new behaviours, bugs and edge cases. When these changes are pushed to `main`, the SDKs are cloned locally (locally to the github action running) and their respective tests are run. These tests are set up and run by copies of the SDK test workflows - see [sdk-test-data workflow](https://github.com/Eppo-exp/sdk-test-data/blob/main/.github/workflows/test-sdks.yml). There are a number of limitations to this setup:
- Test steps are copied from the SDK’s respective workflows; changes to the SDK test workflows need to be replicated in sdk-test-data and …
> feat: run eppo-multiplatform tests for in-flight changes

- package-testing/dotnet-sdk-relay/EppoSDKRelay/AssignmentLogger.cs
- package-testing/dotnet-sdk-relay/EppoSDKRelay/Controllers/AssignmentController.cs
- package-testing/dotnet-sdk-relay/EppoSDKRelay/Controllers/BanditController.cs
- package-testing/dotnet-sdk-relay/EppoSDKRelay/Controllers/JsonControllerBase.cs
- package-testing/dotnet-sdk-relay/EppoSDKRelay/DTO/AttributeSet.cs
- package-testing/dotnet-sdk-relay/EppoSDKRelay/DTO/BanditActionRequest.cs
- package-testing/dotnet-sdk-relay/EppoSDKRelay/EppoSDKRelay.csproj
- package-testing/dotnet-sdk-relay/EppoSDKRelay/Program.cs
- package-testing/dotnet-sdk-relay/EppoSDKRelay/Startup.cs
🎟️ Fixes: FF-3635
Some SDKs allow passing <String, Object> for numeric attributes (for subjects and actions when evaluating bandits). This was recently added to the `ContextAttributes` helper class in the dotnet SDK.
When debugging, having the full bandit and assignment logs returned to the test runner is critical
- use BaseUrl instead of host/port in relay runner to conform to convention
- Return bandit and assignment logs in the test responses
- Handle the Categorical and Numeric attributes separately, using the new `ContextAttributes` API
- Prior to this change, the incorrect handling of attributes (to get around the lack of support for dynamic typing) the test for **Imogene** fails (see attached). After this change, the attributes are correctly sorted and converted (as can be seen in …
> fix: bandit attributes, logs, and baseUrl in dotnet SDK relay

- .github/workflows/test-sdks-remote.yml
- .github/workflows/test-sdks.yml
🎟️ towards FF-3085
Ticket FF-3085
👯‍♂️ **Related PRs**
- [sdk-common-jvm](https://github.com/Eppo-exp/sdk-common-jdk/pull/72)
- #57
- #58
- #59 
Changes are often made to the [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data) repository to capture new behaviours, bugs and edge cases. When these changes are pushed to `main`, the SDKs are cloned locally (locally to the github action running) and their respective tests are run. These tests are set up and run by copies of the SDK test workflows - see [sdk-test-data workflow](https://github.com/Eppo-exp/sdk-test-data/blob/main/.github/workflows/test-sdks.yml). There are a number of limitations to this setup:
- Test steps are copied from the SDK’s respective workflows; changes to the SDK test workflows need to be replicated in …
> feat: local and remote trigger Java common SDK testing

- configuration-wire/precomputed-v1-deobfuscated.json
- configuration-wire/precomputed-v1.json
I believe these should match
https://github.com/Eppo-exp/js-sdk-common/blob/b1048a32587a809bed351af07185592c9f774150/src/types.ts#L5-L8
```typescript
export type ContextAttributes = {
numericAttributes: Attributes;
categoricalAttributes: Attributes;
};
```
> fix: context attribute keys in precomputed config wire

- .github/workflows/test-sdk-packages.yml
- .github/workflows/test-server-sdk.yml
- package-testing/php-sdk-relay/docker-run.sh
- package-testing/python-sdk-relay/.gitignore
- package-testing/python-sdk-relay/Dockerfile
- package-testing/python-sdk-relay/README.md
- package-testing/python-sdk-relay/docker-run.sh
- package-testing/python-sdk-relay/requirements.txt
- package-testing/python-sdk-relay/src/server.py
- package-testing/sdk-test-runner/README.md
- package-testing/sdk-test-runner/test-sdk.sh
In order to performed packaged testing on the python SDK, a relay server is needed. This server receives requests from the test runner, runs flag and bandit evaluations and returns responses. The server spec is published - this lets us have a single test runner for all client and server languages.
Creates a python relay server.
✔️ flag evaluation
✖️ bandit evaluation - skipped in this PR pending support for dynamic values which is in-progress
> python packaged server tests (FF-3494)

- package-testing/sdk-test-runner/package.json
- package-testing/sdk-test-runner/src/app.ts
nested tests failures are not currently helpful:
```
fail banner_bandit_flag_uk_only[charlie]: [object Object] != [object Object]
fail banner_bandit_flag_uk_only[debra]: [object Object] != [object Object]
fail banner_bandit_flag_uk_only[erica]: [object Object] != [object Object]
fail banner_bandit_flag_uk_only[frenkie]: [object Object] != [object Object]
fail banner_bandit_flag_uk_only[gerard]: [object Object] != [object Object]
```
deployed this branch and re-ran failing branch:
```
fail banner_bandit_flag[frenkie]:
Expected: ***
"variation": "banner_bandit",
"action": "puma"
***
Received: ***
"action": null,
"variation": "default"
***
fail banner_bandit_flag[gerard]:
Expected: ***
"variation": "banner_bandit",
"action": "nike"
***
Received: ***
"action": null,
"variation": "default"
*** …
```
> show json serialized diff of test and expectations

- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
- ufc/tests/test-special-characters.json
🎟️ **Ticket:** [FF-3763 - Update shared SDK test data to have a test case for special characters](https://linear.app/eppo/issue/FF-3763/update-shared-sdk-test-data-to-have-a-test-case-for-special-characters)
🗨️ **Slack Thread:** ["...flag text encoding problem..."](https://eppo-group.slack.com/archives/C0541NTN6QH/p1735566355776199)
_Description:_
SDKs need to be able to handle special, non-ASCII characters. This PR adds a test that checks that by using strings with characters from a variety of languages as well as emojis, which all have non-ASCII values.
> Include test case for special characters

- .github/workflows/test-sdk-packages.yml
This was broken and package tests were not running. It is expected that the nodejs relay server is not starting, we will fix that later.
**reviewers** - please merge after approval.
> bug: fix broken test-sdk-packages github workflow in nodejs block

- README.md
- obfuscation/obfuscation.helper.ts
- obfuscation/obfuscation.spec.ts
- obfuscation/ufc.dto.ts
- package.json
- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
- ufc/tests/test-string-with-special-characters.json
Eppo Internal:
🎟️ Ticket: [FF-4069 - Adjust Shared SDK Test Data to Ensure SDKs can handle non-alphanumeric characters in String values](https://linear.app/eppo/issue/FF-4069/adjust-shared-sdk-test-data-to-ensure-sdks-can-handle-non-alphanumeric)
Description:
SDKs need to be able to handle special characters in values for the variations of type STRING. This PR adds a test cases to check all possible allowed special characters as values of the variations. Test cases cover single inclusion of special character, multiple special characters divided by regular ones, multiple repeating special characters as a whole variation value.
> [FF-4069] Update plain and obfuscated configs for flags for variation of type STRING with special characters in values

- .github/workflows/validate-test-data.yml
upgrade to v4 because actions/cache@v2 is deprecated
https://github.com/Eppo-exp/sdk-test-data/actions/runs/13677237873/job/38240394019
> chore: use actions/cache@v4

- .github/workflows/test-sdk-packages.yml
- package-testing/node-sdk-relay/package.json
- package-testing/node-sdk-relay/src/app.controller.ts
- package-testing/node-sdk-relay/yarn.lock
- package-testing/sdk-test-runner/package.json
- package-testing/sdk-test-runner/src/app.ts
The `node-server-sdk` package test has been failing because the wrong SDK name is specified to the test runner
- Specify the correct name in the GH action
- Check the connected SDK against the expected SDK in the sdk-test-runner
- Return SDK Details from the node sdk relay server (which, combined with the above check would have surfaced this issue immediately)
> fix: correctly specify the SDK name under test for node-server

- .github/workflows/test-sdk-packages.yml
A recent change has surfaced this mismatch
> fix: specify proper python SDK name

- ufc/flags-v1-obfuscated.json
- ufc/flags-v1.json
- ufc/tests/test-json-config-flag.json
:ticket: **Ticket:** [FF-4340 - Update shared test data to include empty JSON object](https://linear.app/eppo/issue/FF-4340/update-shared-test-data-to-include-empty-json-object)
🗨️ Slack Convo: ["...We seem to have a constraint against JSON variations that are the empty object..."](https://eppo-group.slack.com/archives/C04KR1GGE3C)
We want to allow empty JSON objects as variation values. Including as a test case to make sure all SDKs can handle this.
> Test case for empty JSON object variation value

- package-testing/php-sdk-relay/src/AssignmentHandler.php
PHP handles the JSON objects as _associative arrays_ aka hashmaps/dicts/etc. When non-empty, these associative arrays are json_encoded as objects, however, when empty, they are encoded as empty arrays.
> fix: return empty objects instead of empty arrays

- .github/workflows/test-sdks.yml
This allows us to avoid explicitly defining the repo to test in the workflow in the android-sdk, which in turn allows us to accept PR from repository forks
> chore: explicitly test Android Repo on reused workflow call
